name: Build & deploy application to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build  # Lint-Job wird nach dem Build-Job ausgeführt
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npx next lint --fix  # Es wird keine Eingabe mehr benötigt, da die Konfiguration bereits im Repo vorhanden ist

  deploy-production:
    name: Deploy (Production)
    needs: lint  # Der Deploy-Job hängt jetzt nur vom Lint-Job ab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
